// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service_order.proto

/*
Package service_order is a generated protocol buffer package.

It is generated from these files:
	service_order.proto

It has these top-level messages:
	GetOrdersRequest
	GetOrdersResponse
	Order
*/
package service_order

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetOrdersRequest struct {
	PageIndex int32 `protobuf:"varint,1,opt,name=page_index,json=pageIndex" json:"page_index,omitempty"`
	PageCount int32 `protobuf:"varint,2,opt,name=page_count,json=pageCount" json:"page_count,omitempty"`
}

func (m *GetOrdersRequest) Reset()                    { *m = GetOrdersRequest{} }
func (m *GetOrdersRequest) String() string            { return proto.CompactTextString(m) }
func (*GetOrdersRequest) ProtoMessage()               {}
func (*GetOrdersRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GetOrdersRequest) GetPageIndex() int32 {
	if m != nil {
		return m.PageIndex
	}
	return 0
}

func (m *GetOrdersRequest) GetPageCount() int32 {
	if m != nil {
		return m.PageCount
	}
	return 0
}

type GetOrdersResponse struct {
	Orders []*Order `protobuf:"bytes,1,rep,name=orders" json:"orders,omitempty"`
}

func (m *GetOrdersResponse) Reset()                    { *m = GetOrdersResponse{} }
func (m *GetOrdersResponse) String() string            { return proto.CompactTextString(m) }
func (*GetOrdersResponse) ProtoMessage()               {}
func (*GetOrdersResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetOrdersResponse) GetOrders() []*Order {
	if m != nil {
		return m.Orders
	}
	return nil
}

type Order struct {
	Id         uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Code       string `protobuf:"bytes,2,opt,name=code" json:"code,omitempty"`
	UserId     uint64 `protobuf:"varint,3,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Title      string `protobuf:"bytes,4,opt,name=title" json:"title,omitempty"`
	Price      int64  `protobuf:"varint,5,opt,name=price" json:"price,omitempty"`
	CreateTime string `protobuf:"bytes,6,opt,name=create_time,json=createTime" json:"create_time,omitempty"`
	UpdateTime string `protobuf:"bytes,7,opt,name=update_time,json=updateTime" json:"update_time,omitempty"`
}

func (m *Order) Reset()                    { *m = Order{} }
func (m *Order) String() string            { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()               {}
func (*Order) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Order) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Order) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Order) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Order) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Order) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Order) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *Order) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

func init() {
	proto.RegisterType((*GetOrdersRequest)(nil), "GetOrdersRequest")
	proto.RegisterType((*GetOrdersResponse)(nil), "GetOrdersResponse")
	proto.RegisterType((*Order)(nil), "Order")
}

func init() { proto.RegisterFile("service_order.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 273 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0xed, 0x6e, 0xdb, 0xa5, 0xb3, 0x22, 0xee, 0x28, 0x18, 0x04, 0xb5, 0xf4, 0xd4, 0x53,
	0x0f, 0xbb, 0xbe, 0x81, 0x82, 0xec, 0x49, 0x89, 0xde, 0xcb, 0xda, 0x0c, 0x12, 0x70, 0x9b, 0x9a,
	0xa4, 0xe2, 0x73, 0xf9, 0x84, 0x92, 0x89, 0x54, 0xd1, 0x5b, 0xe6, 0x9b, 0x2f, 0x99, 0xe4, 0x0f,
	0x9c, 0x38, 0xb2, 0xef, 0xba, 0xa3, 0xd6, 0x58, 0x45, 0xb6, 0x19, 0xac, 0xf1, 0xa6, 0x7a, 0x80,
	0xe3, 0x3b, 0xf2, 0xf7, 0x81, 0x38, 0x49, 0x6f, 0x23, 0x39, 0x8f, 0x17, 0x00, 0xc3, 0xee, 0x85,
	0x5a, 0xdd, 0x2b, 0xfa, 0x10, 0x49, 0x99, 0xd4, 0x99, 0x2c, 0x02, 0xd9, 0x06, 0x30, 0xb5, 0x3b,
	0x33, 0xf6, 0x5e, 0xcc, 0x7e, 0xda, 0x37, 0x01, 0x54, 0x1b, 0x58, 0xfd, 0x3a, 0xd1, 0x0d, 0xa6,
	0x77, 0x84, 0x97, 0x90, 0xf3, 0x54, 0x27, 0x92, 0x72, 0x5e, 0x2f, 0xd7, 0x79, 0xc3, 0x82, 0xfc,
	0xa6, 0xd5, 0x67, 0x02, 0x19, 0x13, 0x3c, 0x82, 0x99, 0x56, 0x3c, 0x34, 0x95, 0x33, 0xad, 0x10,
	0x21, 0xed, 0x8c, 0x22, 0x9e, 0x53, 0x48, 0x5e, 0xe3, 0x19, 0x2c, 0x46, 0x47, 0xb6, 0xd5, 0x4a,
	0xcc, 0x59, 0xcc, 0x43, 0xb9, 0x55, 0x78, 0x0a, 0x99, 0xd7, 0xfe, 0x95, 0x44, 0xca, 0x76, 0x2c,
	0x02, 0x1d, 0xac, 0xee, 0x48, 0x64, 0x65, 0x52, 0xcf, 0x65, 0x2c, 0xf0, 0x0a, 0x96, 0x9d, 0xa5,
	0x9d, 0xa7, 0xd6, 0xeb, 0x3d, 0x89, 0x9c, 0x77, 0x40, 0x44, 0x4f, 0x7a, 0xcf, 0xc2, 0x38, 0xa8,
	0x49, 0x58, 0x44, 0x21, 0xa2, 0x20, 0xac, 0x6f, 0xe1, 0x90, 0xef, 0xfc, 0x18, 0x73, 0xc5, 0x6b,
	0x28, 0xa6, 0x97, 0xe3, 0xaa, 0xf9, 0x9b, 0xeb, 0x39, 0x36, 0xff, 0x82, 0xa9, 0x0e, 0x9e, 0x73,
	0xfe, 0x88, 0xcd, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa8, 0x09, 0x5d, 0x16, 0x9f, 0x01, 0x00,
	0x00,
}
